2012/12/18 05:22:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 D:\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 D:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 D:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 D:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 D:\xampp\htdocs\yii\demo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/demo/index.php?r=gii/model
HTTP_REFERER=http://localhost/yii/demo/index.php?r=gii
---
2012/12/18 05:22:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 D:\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 D:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 D:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 D:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 D:\xampp\htdocs\yii\demo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/demo/index.php?r=gii/model
HTTP_REFERER=http://localhost/yii/demo/index.php?r=gii
---
2012/12/18 05:22:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 D:\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 D:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 D:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 D:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 D:\xampp\htdocs\yii\demo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/demo/index.php?r=gii/model
HTTP_REFERER=http://localhost/yii/demo/index.php?r=gii
---
2012/12/18 05:22:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 D:\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 D:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 D:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 D:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 D:\xampp\htdocs\yii\demo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/demo/index.php?r=gii/model
HTTP_REFERER=http://localhost/yii/demo/index.php?r=gii
---
2012/12/18 05:26:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "useáº»".' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('use???')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yii\demo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/demo/index.php?r=use%E1%BA%BB
---
